### ISSUE TITLE
Error after update to 12.3

### ISSUE THREAD

**Issue by karimone** [mariocesar/sorl-thumbnail#378]
FYI I got this error on my project (was fine with 12.2). Anyone have any idea if it's an easy fix?
```
 File "/usr/local/lib/python2.7/dist-packages/sorl/thumbnail/default.py", line 14, in _setup
    self._wrapped = get_module_class(settings.THUMBNAIL_KVSTORE)()
  File "/usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py", line 69, in get_module_class

ImproperlyConfigured: Error importing module sorl.thumbnail.kvstores.cached_db_kvstore: "cannot import name get_cache"
```

**Comment by mariocesar** [comment]
Can you try entering a shell with `python manage.py shell` and do the following

```
>>> from sorl.thumbnail.compat import get_cache
```

Also, before you do that try also to uninstall the previous sorl-thumbnail version

**Comment by karimone** [comment]
I think everything is fine, was another problem in my production server. Thanks @mariocesar
